<a href="https://colab.research.google.com/github/hansensean123-cell/Sean-Hansen/blob/main/Assignments/assignment_06_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IS 4487 Assignment 6: Data Cleaning with Airbnb Listings

In this assignment, you will:
- Load a raw Airbnb listings dataset
- Identify and resolve missing or inconsistent data
- Decide what data to drop, keep, or clean
- Save a clean dataset to use in Assignment 7

## Why This Matters

Data cleaning is one of the most important steps in any analysis ‚Äî but it's often the least visible. Airbnb hosts, managers, and policy teams rely on clean data to make decisions. This assignment gives you experience cleaning raw data and justifying your choices so others can understand your process.

<a href="https://colab.research.google.com/github/Stan-Pugsley/is_4487_base/blob/main/Assignments/assignment_06_data_cleaning.ipynb" target="_parent">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## Dataset Description

The dataset you'll be using is a **detailed Airbnb listing file**, available from [Inside Airbnb](https://insideairbnb.com/get-the-data/).

Each row represents one property listing. The columns include:

- **Host attributes** (e.g., host ID, host name, host response time)
- **Listing details** (e.g., price, room type, minimum nights, availability)
- **Location data** (e.g., neighborhood, latitude/longitude)
- **Property characteristics** (e.g., number of bedrooms, amenities, accommodates)
- **Calendar/booking variables** (e.g., last review date, number of reviews)

üìå The schema is consistent across cities, so you can expect similar columns regardless of the location you choose.

## 1. Choose a City & Upload Your Dataset

üì• Follow these steps:

1. Go to: [https://insideairbnb.com/get-the-data/](https://insideairbnb.com/get-the-data/)
2. Choose a city you‚Äôre interested in.
3. Download the file named: **`listings.csv.gz`** under that city.
4. In your notebook:
   - Open the left sidebar
   - Click the folder icon üìÅ
   - Click the upload icon ‚¨ÜÔ∏è and choose your `listings.csv.gz` file
5. Use the file path `/content/listings.csv.gz` when loading your data.
6. Import standard libraries (`pandas`, `numpy`, `seaborn`, `matplotlib`)

In [4]:
# Import necessary libraries üîß

In [3]:
# Load your uploaded file (path "/content/listings.csv.gz") üîß
df = pd.read_csv("/listings.csv.gz")
display(df.head())

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,155305,https://www.airbnb.com/rooms/155305,20250617145515,2025-06-17,city scrape,Cottage! BonPaul + Sharky's Hostel,West Asheville Cottage within walking distance...,"We are within easy walk of pubs, breweries, mu...",https://a0.muscache.com/pictures/hosting/Hosti...,746673,...,4.74,4.92,4.58,NaN,t,8,2,3,3,2.69
1,197263,https://www.airbnb.com/rooms/197263,20250617145515,2025-06-17,city scrape,Tranquil Room & Private Bath,"This is a comfy, peaceful and clean room with ...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,961396,...,4.93,4.86,4.98,NaN,f,2,1,1,0,0.56
2,209068,https://www.airbnb.com/rooms/209068,20250617145515,2025-06-17,city scrape,Terrace Cottage,Located in one of Asheville's oldest historic ...,Our beautiful Grove Park Historic District clo...,https://a0.muscache.com/pictures/1829924/9f3bf...,1029919,...,4.98,4.94,4.80,NaN,f,1,1,0,0,0.40
3,246315,https://www.airbnb.com/rooms/246315,20250617145515,2025-06-17,city scrape,Asheville Dreamer's Cabin,"Hi there,<br />I am usually here half of each ...",NaN,https://a0.muscache.com/pictures/5908617/cfe79...,1292070,...,4.65,4.67,4.59,NaN,f,3,2,1,0,0.32
4,314540,https://www.airbnb.com/rooms/314540,20250617145515,2025-06-17,city scrape,Asheville Urban Farmhouse Entire Home 4.6 mi t...,Farmhouse in the city is OPEN! This charming 1...,City vibes with country appeal. Peaceful neigh...,https://a0.muscache.com/pictures/hosting/Hosti...,381660,...,4.97,4.91,4.94,NaN,t,1,1,0,0,0.22

## 2. Explore Missing Values

Business framing:  

Stakeholders don‚Äôt like surprises in the data. Missing values can break dashboards, confuse pricing models, or create blind spots for host managers.

Explore how complete your dataset is:

- Count missing values in each column
- Visualize missingness if helpful (e.g., heatmap, barplot)
- Flag columns that might not be usable due to missing data

### In your markdown:
1. What are the top 3 columns with the most missing values?
2. Which ones are likely to create business issues?
3. Which could be safely ignored or dropped?

In [5]:
# Add code here üîß

license                         2876
calendar_updated                2876
neighbourhood_group_cleansed    2876
host_neighbourhood              1792
host_about                      1025
neighborhood_overview            952
neighbourhood                    952
host_response_time               442
host_response_rate               442
host_location                    440
price                            340
estimated_revenue_l365d          340
beds                             339
bathrooms                        331
review_scores_cleanliness        263
review_scores_location           263
first_review                     263
review_scores_communication      263
review_scores_rating             263
review_scores_accuracy           263
dtype: int64

### ‚úçÔ∏è Your Response: üîß
1.License (2876 missing values), calendar updated (2876 missing values), and neighborhood group cleansed (2876 missing values)

2. Missing price information would make it impossible to analyze pricing trends. Missing bed and bathroom amounts would impact search filters affecting booking decisions. Review scores would make it hard to see the listing quality and host performance.

3.License, calendar updated, and neighbourhood group cleaned are all empty, so it wouldn't result in any loss of information for analysis.

## 3. Drop Columns That Aren‚Äôt Useful

Business framing:  

Not every column adds value. Analysts often remove columns that are too empty, irrelevant, or repetitive ‚Äî especially when preparing data for others.

Make a decision:

- Choose 2‚Äì4 columns to drop from your dataset
- Document your reasons for each one
- Confirm they're gone with `.head()` or `.info()`

### In your markdown:
1. Which columns did you drop?
2. Why were they not useful from a business perspective?
3. What could go wrong if you left them in?

In [6]:
# Add code here üîß

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2876 entries, 0 to 2875
Data columns (total 76 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            2876 non-null   int64
 1   listing_url                                   2876 non-null   object
 2   scrape_id                                     2876 non-null   int64
 3   last_scraped                                  2876 non-null   object
 4   source                                        2876 non-null   object
 5   name                                          2876 non-null   object
 6   description                                   2826 non-null   object
 7   neighborhood_overview                         1924 non-null   object
 8   picture_url                                   2876 non-null   object
 9   host_id                                       2876 non-null   int64
 10  host_url                                      2876 non-null   object
 11  host_name                                     2876 non-null   object
 12  host_since                                    2876 non-null   object
 13  host_location                                 2436 non-null   object
 14  host_about                                    1851 non-null   object
 15  host_response_time                            2434 non-null   object
 16  host_response_rate                            2434 non-null   object
 17  host_acceptance_rate                          2654 non-null   object
 18  host_is_superhost                             2830 non-null   object
 19  host_thumbnail_url                            2876 non-null   object
 20  host_picture_url                              2876 non-null   object
 21  host_neighbourhood                            1084 non-null   object
 22  host_listings_count                           2876 non-null   int64
 23  host_total_listings_count                     2876 non-null   int64
 24  host_verifications                            2876 non-null   object
 25  host_has_profile_pic                          2876 non-null   object
 26  host_identity_verified                        2876 non-null   object
 27  neighbourhood                                 1924 non-null   object
 28  neighbourhood_cleansed                        2876 non-null   int64
 29  latitude                                      2876 non-null   float64
 30  longitude                                     2876 non-null   float64
 31  property_type                                 2876 non-null   object
 32  room_type                                     2876 non-null   object
 33  accommodates                                  2876 non-null   int64
 34  bathrooms                                     2545 non-null   float64
 35  bathrooms_text                                2876 non-null   object
 36  bedrooms                                      2842 non-null   float64
 37  beds                                          2537 non-null   float64
 38  amenities                                     2876 non-null   object
 39  price                                         2536 non-null   object
 40  minimum_nights                                2876 non-null   int64
 41  maximum_nights                                2876 non-null   int64
 42  minimum_minimum_nights                        2876 non-null   int64
 43  maximum_minimum_nights                        2876 non-null   int64
 44  minimum_maximum_nights                        2876 non-null   int64
 45  maximum_maximum_nights                        2876 non-null   int64
 46  minimum_nights_avg_ntm                        2876 non-null   float64
 47  maximum_nights_avg_ntm                        2876 non-null   float64
 48  has_availability                              2836 non-null   object
 49  availability_30                               2876 non-null   int64
 50  availability_60                               2876 non-null   int64
 51  availability_90                               2876 non-null   int64
 52  availability_365                              2876 non-null   int64
 53  calendar_last_scraped                         2876 non-null   object
 54  number_of_reviews                             2876 non-null   int64
 55  number_of_reviews_ltm                         2876 non-null   int64
 56  number_of_reviews_l30d                        2876 non-null   int64
 57  availability_eoy                              2876 non-null   int64
 58  number_of_reviews_ly                          2876 non-null   int64
 59  estimated_occupancy_l365d                     2876 non-null   int64
 60  estimated_revenue_l365d                       2536 non-null   float64
 61  first_review                                  2613 non-null   object
 62  last_review                                   2613 non-null   object
 63  review_scores_rating                          2613 non-null   float64
 64  review_scores_accuracy                        2613 non-null   float64
 65  review_scores_cleanliness                     2613 non-null   float64
 66  review_scores_checkin                         2613 non-null   float64
 67  review_scores_communication                   2613 non-null   float64
 68  review_scores_location                        2613 non-null   float64
 69  review_scores_value                           2613 non-null   float64
 70  instant_bookable                              2876 non-null   object
 71  calculated_host_listings_count                2876 non-null   int64
 72  calculated_host_listings_count_entire_homes   2876 non-null   int64
 73  calculated_host_listings_count_private_rooms  2876 non-null   int64
 74  calculated_host_listings_count_shared_rooms   2876 non-null   int64
 75  reviews_per_month                             2613 non-null   float64
dtypes: float64(16), int64(27), object(33)
memory usage: 1.7+ MB

### ‚úçÔ∏è Your Response: üîß
1.I dropped license, calendar updated, and neighbourhood group cleansed since they are all empty.

2.All of those columns were empty with no information so there is no need to have them.

3.It puts more clutter in the dataset which means slower processing and increased memory usage. Potential errors in analysis can arise and make the data more skewed.

## 4. Fill or Fix Values in Key Columns

Business framing:  

Let‚Äôs say your manager wants to see a map of listings with prices and review scores. If key fields are blank, the map won‚Äôt work. But not all missing values should be filled the same way.

- Choose 2 columns with missing values
- Use a strategy to fill or flag those values
  - (e.g., median, ‚Äúunknown‚Äù, forward-fill, or a placeholder)
- Explain what you did and why

### In your markdown:
1. What two columns did you clean?
2. What method did you use for each, and why?
3. What risks are there in how you filled the data?

In [7]:
# Your code for converting column data types üîß

/tmp/ipython-input-3637625966.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['price'].fillna(price_median, inplace=True)
/tmp/ipython-input-3637625966.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores_rating'].fillna(review_scores_rating_median, inplace=True)

price                   0
review_scores_rating    0
dtype: int64

### ‚úçÔ∏è Your Response: üîß
1.I cleaned the price and review scores rating columns.

2. I put in the respective median values so the data is less sensitive to outliers when using the mean.

3.Using the mean to fill in missing information can distort the distribution. This is because it makes the distribution narrower and makes it less variable. The median is just an assumed value, so it needs to be taken with a grain of salt.

## 5. Convert and Clean Data Types

Business framing:  

Sometimes columns that look like numbers are actually stored as text ‚Äî which breaks calculations and slows down analysis. Common examples are price columns with dollar signs or availability stored as strings.

- Identify one column with the wrong data type
- Clean and convert it into a usable format (e.g., from string to number)
- Check your work by summarizing or plotting the cleaned column

### In your markdown:
1. What column did you fix?
2. What cleaning steps did you apply?
3. How does this help prepare the data for later use?

In [8]:
# Clean or adjust your dataset üîß

float64

count    2876.000000
mean      174.964882
std       209.258133
min        18.000000
25%        95.000000
50%       128.000000
75%       190.000000
max      6846.000000
Name: price, dtype: float64

### ‚úçÔ∏è Your Response: üîß
1.I cleaned up the price column.

2.I changed the data type from object to numeric then displayed the descriptive stats of it.

3.This helps for later use as I can see the descriptive stats on the price of the airbnb booking and get a better understand of it.

## 6. Remove Duplicate Records

Business framing:  

If a listing appears twice, it could inflate revenue estimates or confuse users. Airbnb needs each listing to be unique and accurate.

- Check for exact duplicate rows
- Also check for duplicate IDs if a unique ID column exists
- Remove duplicates if found and explain your reasoning

### In your markdown:
1. Did you find duplicates?
2. How did you decide what to drop or keep?
3. Why are duplicates risky for Airbnb teams?

In [9]:
# Add code here üîß

Number of exact duplicate rows: 0
Number of duplicate IDs: 0
No duplicate IDs found.
Number of rows after removing duplicates: 2876

### ‚úçÔ∏è Your Response: üîß üîß
1.I didn't find any duplicate rows.

2. I didn't find any duplicates so there wasn't a decision.

3.Duplicates are risky because you don't want the same listing available at one time as that would lead to double-booking and a lot of confusion for hosts and guests.

## 7. Export Cleaned Data

Before wrapping up, export your cleaned Airbnb dataset to a CSV file. You'll need this file for **Assignment 7**, where you'll perform data transformation techniques.

Make sure your data has:
- Cleaned and consistent column values
- Proper data types for each column
- Any unnecessary columns removed

This file should be the version of your dataset that you‚Äôd feel confident sharing with a teammate or using for deeper analysis.



```
# Make sure your cleaned DataFrame is named appropriately
# For example, if your cleaned dataset is stored in a DataFrame called 'df_cleaned':

# Export the cleaned DataFrame to a CSV file
df_cleaned.to_csv("cleaned_airbnb_data.csv", index=False)

# Explanation:
# - "cleaned_airbnb_data.csv" is the name of the file that will be saved
# - index=False prevents pandas from writing row numbers into the CSV
# - The file will be saved to your working directory (in Colab, you'll need to download it manually)

```

In [13]:
# export csv here üîß

## 8. Final Reflection

You‚Äôve just cleaned a real-world Airbnb dataset ‚Äî the kind of work that happens every day in analyst and data science roles.

Before you move on to data transformation in Assignment 7, take a few moments to reflect on the decisions you made and what you learned.

### In your markdown:
1. What was the most surprising or challenging part of cleaning this dataset?
2. How did you decide which data to drop, fix, or keep?
3. What‚Äôs one way a business team (e.g., hosts, pricing analysts, platform ops) might benefit from the cleaned version of this data?
4. If you had more time, what would you explore or clean further?
5. How does this relate to your customized learning outcome you created in canvas?


Write your response clearly in full sentences. No more than a few sentences required per response.

## Submission Instructions
‚úÖ Checklist:
- All code cells run without error
- All markdown responses are complete
- Submit on Canvas as instructed

In [20]:
!jupyter nbconvert --to html "/assignment_06_data_cleaning.ipynb"

[NbConvertApp] Converting notebook /assignment_06_data_cleaning.ipynb to html
[NbConvertApp] Writing 318094 bytes to /assignment_06_data_cleaning.html